import { Clock3, Activity } from 'lucide-react';
import { integer, pct, time } from './domain';
import type { Snapshot } from './useResults';
export function History({history}:{history:Snapshot[]}) {
  const chart=history.filter(s=>s.percent!==null);
  const start=chart.length?Date.parse(chart[0].at):0,end=chart.length?Date.parse(chart.at(-1)!.at):0;
  const points=chart.map(s=>`${20+(end===start?0:(Date.parse(s.at)-start)/(end-start)*240)},${115-(s.percent??0)}`).join(' ');
  return <><section className="panel history-panel"><div className="panel-heading"><div><p className="eyebrow">NESTE DISPOSITIVO</p><h2>Ao longo da apuração</h2></div><Activity size={17} className="muted"/></div>{chart.length<2?<div className="history-empty"><Clock3 size={23}/><p>{chart.length?'Primeira consulta registrada.':'Aguardando a primeira consulta.'}</p><span>O gráfico aparece quando chegar uma nova geração do TSE.</span></div>:<><svg viewBox="0 0 280 145" role="img" aria-label="Histórico observado de urnas apuradas"><line x1="20" y1="15" x2="260" y2="15" className="chart-grid"/><line x1="20" y1="65" x2="260" y2="65" className="chart-grid"/><line x1="20" y1="115" x2="260" y2="115" className="chart-grid"/><text x="0" y="19" className="chart-label">100</text><text x="0" y="69" className="chart-label">50</text><text x="5" y="119" className="chart-label">0</text><polyline points={points} fill="none" stroke="#b4e793" strokeWidth="2.3" strokeLinejoin="round"/><text x="20" y="138" className="chart-label">{time(chart[0].at).slice(0,5)}</text><text x="260" y="138" textAnchor="end" className="chart-label">{time(chart.at(-1)!.at).slice(0,5)}</text></svg><p className="small muted">Percentual de seções totalizadas · consultas observadas aqui.</p></>}</section>
  <section className="panel updates-panel"><div className="panel-heading"><div><p className="eyebrow">DADOS OBSERVADOS</p><h2>Últimas atualizações</h2></div><Clock3 size={17} className="muted"/></div>{history.length?<ol>{history.slice(-5).reverse().map(s=><li key={s.at}><span className="update-time mono">{time(s.at).slice(0,5)}</span><div><p className="mono">{pct(s.percent)} apuradas</p><span className="small muted">{integer.format(s.counted)} seções totalizadas</span></div></li>)}</ol>:<p className="small muted empty-message">As novas consultas aparecerão aqui.</p>}<p className="small muted history-note">Histórico local desde sua primeira visita; não é um histórico completo do TSE.</p></section></>;
}
