import React, { useCallback, useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, Check, CheckCheck, ChevronDown, CircleHelp, Clock3, ExternalLink, Globe2, MapPin, Radio, RefreshCw, Search, ShieldCheck, Vote, WifiOff, X } from 'lucide-react';
import type { Result } from './types';
import './style.css';

const states:Record<string,string>={br:'Brasil',ac:'Acre',al:'Alagoas',ap:'Amapá',am:'Amazonas',ba:'Bahia',ce:'Ceará',df:'Distrito Federal',es:'Espírito Santo',go:'Goiás',ma:'Maranhão',mt:'Mato Grosso',ms:'Mato Grosso do Sul',mg:'Minas Gerais',pa:'Pará',pb:'Paraíba',pr:'Paraná',pe:'Pernambuco',pi:'Piauí',rj:'Rio de Janeiro',rn:'Rio Grande do Norte',rs:'Rio Grande do Sul',ro:'Rondônia',rr:'Roraima',sc:'Santa Catarina',sp:'São Paulo',se:'Sergipe',to:'Tocantins'};
const offices:Record<number,string>={1:'Presidente',3:'Governador',5:'Senador',6:'Deputado federal',7:'Deputado estadual',8:'Deputado distrital'};
const integer=new Intl.NumberFormat('pt-BR');
const decimal=new Intl.NumberFormat('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});
const pct=(value:number|null|undefined)=>value==null?'—':`${decimal.format(value)}%`;
const time=(iso:string|null)=>iso?new Date(iso).toLocaleTimeString('pt-BR',{timeZone:'America/Sao_Paulo',hour:'2-digit',minute:'2-digit',second:'2-digit'}):'—';
function initialFilters() {
  const params=new URLSearchParams(location.search);
  const uf=params.get('uf')??'br';const office=Number(params.get('office')??'1');
  return {uf:states[uf]?uf:'br',office:offices[office]&&!(uf==='br'&&office!==1)&&!(office===8&&uf!=='df')&&!(office===7&&uf==='df')?office:1};
}
function App() {
  const [filters,setFilters]=useState(initialFilters);
  const [data,setData]=useState<Result|null>(null);
  const [error,setError]=useState('');
  const [loading,setLoading]=useState(true);
  const [offline,setOffline]=useState(!navigator.onLine);
  const [tick,setTick]=useState(Date.now());
  const [search,setSearch]=useState('');
  const [limit,setLimit]=useState(20);
  const abort=useRef<AbortController|null>(null);
  const load=useCallback(async()=>{
    abort.current?.abort();const controller=new AbortController();abort.current=controller;
    setLoading(true);
    try {
      const response=await fetch(`/api/results?uf=${filters.uf}&office=${filters.office}`,{signal:controller.signal});
      const payload=await response.json();
      if(!response.ok)throw new Error(payload.error??'Não foi possível consultar o TSE.');
      if(controller.signal.aborted)return;
      setData(payload);setError('');
    } catch(e) {if(!controller.signal.aborted)setError(!navigator.onLine?'Você está sem conexão. Reconecte para atualizar.':e instanceof Error?e.message:'Não foi possível atualizar.');}
    finally {if(!controller.signal.aborted)setLoading(false);}
  },[filters]);
  useEffect(()=>{
    setData(null);setSearch('');setLimit(20);setError('');void load();
    const interval=setInterval(()=>{if(document.visibilityState==='visible'&&navigator.onLine)void load();},60_000);
    const visible=()=>{if(document.visibilityState==='visible'&&navigator.onLine)void load();};
    document.addEventListener('visibilitychange',visible);
    const params=new URLSearchParams({uf:filters.uf,office:String(filters.office)});
    history.replaceState(null,'',`?${params}`);
    return()=>{clearInterval(interval);abort.current?.abort();document.removeEventListener('visibilitychange',visible);};
  },[load,filters]);
  useEffect(()=>{const timer=setInterval(()=>setTick(Date.now()),1000);const online=()=>{setOffline(!navigator.onLine);if(navigator.onLine)void load();};window.addEventListener('online',online);window.addEventListener('offline',online);return()=>{clearInterval(timer);window.removeEventListener('online',online);window.removeEventListener('offline',online);};},[load]);
  const age=data?.sourceTime?(tick-Date.parse(data.sourceTime))/60_000:0;
  const old=!!data&&(data.stale||!!error||offline||age>5);
  const progress=data?.sections.percent??0;
  const candidates=data?.candidates.filter(c=>`${c.name} ${c.party} ${c.number}`.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(search.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()))??[];
  const next=data?Math.max(0,60-Math.floor((tick-Date.parse(data.fetchedAt))/1000)):60;
  const proportional=[6,7,8].includes(filters.office);
  const availableOffices=Object.entries(offices).filter(([id])=>filters.uf==='br'?id==='1':filters.uf==='df'?id!=='7':id!=='8');
  const officialUrl=`https://resultados.tse.jus.br/oficial/app/index.html#/eleicao/${filters.office===1?'6257':'6259'}/uf/${filters.uf}/cargo/${filters.office}/vis/nominal/resultados`;
  return <div className="min-h-screen">
    <header className="border-b border-[#dedfd6] bg-[#fbfaf6]"><div className="mx-auto flex max-w-6xl items-center justify-between gap-3 px-5 py-5 sm:px-8">
      <a href="/" className="flex items-center gap-3" aria-label="Apuração 2026, início"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#152a27] text-[#d7f28a]"><Vote size={23}/></span><span className="text-lg font-bold tracking-tight">apuração<span className="ml-1 font-normal text-[#6e7771]">2026</span></span></a>
      <span className="rounded-full border border-[#dedfd6] px-3 py-1.5 text-[11px] font-semibold tracking-widest text-[#69756e]">GRUPO B</span>
    </div></header>
    <main className="mx-auto max-w-6xl px-5 pb-10 pt-7 sm:px-8 sm:pt-10">
      <div className="mb-7 flex flex-wrap items-end justify-between gap-5"><div><p className="mb-2 text-xs font-semibold uppercase tracking-[.18em] text-[#71816c]">4 de outubro · 1º turno</p><h1 className="text-[32px] font-semibold leading-tight tracking-[-.04em] sm:text-[44px]">Cada voto conta.</h1><p className="mt-2 text-sm text-[#6e7771]">Acompanhe a apuração com dados oficiais do TSE.</p></div><div className={`status-badge ${old||offline?'status-warning':''}`}><span className="status-dot"/>{offline?'Sem conexão':old?'Últimos dados disponíveis':loading?'Consultando TSE':data?.final?'Totalização finalizada':'Atualização automática'}</div></div>
      <section aria-label="Filtros da apuração" className="mb-6 grid gap-3 sm:grid-cols-2">
        <label className="filter-box"><span className="filter-icon"><MapPin size={19}/></span><span className="min-w-0 flex-1"><span className="filter-label">Localidade</span><select aria-label="Localidade" value={filters.uf} onChange={e=>{const uf=e.target.value;setFilters({uf,office:uf==='br'?1:uf==='df'&&filters.office===7?8:uf!=='df'&&filters.office===8?7:filters.office});}}>{Object.entries(states).map(([uf,name])=><option key={uf} value={uf}>{name}{uf==='br'?' · resultado nacional':` · ${uf.toUpperCase()}`}</option>)}</select></span><ChevronDown size={18} className="pointer-events-none text-[#71816c]"/></label>
        <label className="filter-box"><span className="filter-icon"><Vote size={19}/></span><span className="min-w-0 flex-1"><span className="filter-label">Cargo</span><select aria-label="Cargo" value={filters.office} onChange={e=>setFilters({...filters,office:Number(e.target.value)})}>{availableOffices.map(([id,name])=><option key={id} value={id}>{name}{id==='5'?' · 2 vagas':''}</option>)}</select></span><ChevronDown size={18} className="pointer-events-none text-[#71816c]"/></label>
      </section>
      {filters.uf==='br'&&<p className="-mt-3 mb-5 text-xs text-[#6e7771]">Selecione um estado para acompanhar governador, senador e deputados.</p>}
      {(error||offline||data?.warning||old)&&<div role="status" className="mb-5 flex items-start gap-3 rounded-xl border border-[#ead6a7] bg-[#fff8e8] p-4 text-sm text-[#745a24]">{offline?<WifiOff size={19} className="mt-0.5 shrink-0"/>:<Clock3 size={19} className="mt-0.5 shrink-0"/>}<p>{error||data?.warning||(offline?'Você está sem conexão. Mostrando a última consulta.':'O arquivo do TSE foi gerado há mais de 5 minutos. Mostrando a última atualização disponível.')} {data&&'Os números abaixo são da última consulta bem-sucedida.'}</p></div>}
      <div className="grid items-start gap-5 lg:grid-cols-[minmax(0,1fr)_320px]">
        <section className="overflow-hidden rounded-2xl bg-[#152a27] p-6 text-[#fbfaf6] sm:p-8 lg:col-span-2" aria-label="Progresso da apuração"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="mb-2 flex items-center gap-2 text-xs text-[#b9c7bb]"><Globe2 size={14}/><span>{states[filters.uf]} <span className="mx-1 opacity-50">/</span> {offices[filters.office]}</span></div><h2 className="text-sm font-medium text-[#d8e0d6]">Urnas apuradas <span className="font-normal opacity-60">· seções totalizadas</span></h2></div><span className="rounded-full border border-white/15 px-3 py-1.5 text-[11px] font-medium text-[#d7f28a]">{data?.final?'TOTALIZAÇÃO FINALIZADA':'RESULTADO PARCIAL'}</span></div><div className="my-5 flex flex-wrap items-baseline gap-x-4 gap-y-1"><p className="font-mono text-[46px] font-medium leading-none tracking-[-.06em] text-[#d7f28a] sm:text-[62px]" data-testid="progress">{data?pct(data.sections.percent):'—'}</p><span className="text-xs text-[#b9c7bb] sm:text-sm">{data?`${integer.format(data.sections.counted)} de ${integer.format(data.sections.total)} seções`:'Aguardando os dados do TSE'}</span></div><div role="progressbar" aria-label="Urnas apuradas" aria-valuemin={0} aria-valuemax={100} aria-valuenow={data?.sections.percent??undefined} className="h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-[#d7f28a] transition-[width] duration-700" style={{width:`${Math.min(100,progress)}%`}}/></div><div className="mt-4 flex flex-wrap items-center justify-between gap-2 text-[11px] text-[#b9c7bb]"><span className="flex items-center gap-1.5"><Clock3 size={13}/>TSE: {time(data?.sourceTime??null)} <span className="opacity-60">· Brasília</span></span><span>{data?.final?'Todas as seções totalizadas':data?`${pct(Math.max(0,100-progress))} aguardando totalização`:'Atualiza a cada 60 segundos'}</span></div></section>
        <section className="rounded-2xl border border-[#e0e2d9] bg-white" aria-label="Resultados dos candidatos"><div className="flex items-start justify-between gap-4 border-b border-[#eceee7] p-5 sm:p-6"><div><h2 className="text-lg font-semibold tracking-tight">{offices[filters.office]}</h2><p className="mt-1 text-xs text-[#748077]">{proportional?'Votação nominal · ordem de votos':'Candidatos · ordem de votos'}</p></div><span className="flex items-center gap-1.5 rounded-full bg-[#f1f4ec] px-2.5 py-1.5 text-[11px] text-[#576652]"><ShieldCheck size={13}/>TSE</span></div>
          {proportional&&<div className="mx-5 mt-5 flex items-center gap-2 rounded-lg border border-[#e3e6dc] px-3 text-[#778273]"><Search size={17}/><input className="h-11 min-w-0 flex-1 bg-transparent text-sm outline-none" aria-label="Buscar candidato" placeholder="Nome, partido ou número" value={search} onChange={e=>{setSearch(e.target.value);setLimit(20);}}/>{search&&<button aria-label="Limpar busca" onClick={()=>setSearch('')} className="flex h-10 w-10 items-center justify-center"><X size={16}/></button>}</div>}
          {!data&&loading?<div className="p-6" aria-label="Carregando resultados"><div className="skeleton mb-5 h-12 rounded-lg"/><div className="skeleton mb-5 h-12 rounded-lg"/><div className="skeleton h-12 rounded-lg"/></div>:!data?<div className="p-8 text-center"><Radio className="mx-auto mb-3 text-[#71816c]"/><h3 className="font-medium">Aguardando dados oficiais</h3><p className="mt-2 text-sm text-[#748077]">A consulta será refeita automaticamente. Você também pode abrir o TSE abaixo.</p></div>:!data.released?<div className="p-8 text-center"><Clock3 className="mx-auto mb-3 text-[#71816c]"/><h3 className="font-medium">Divulgação ainda não liberada</h3><p className="mt-2 text-sm text-[#748077]">O TSE ainda não liberou os votos para este resultado.</p></div>:candidates.length===0?<p className="p-8 text-center text-sm text-[#748077]">{search?'Nenhum candidato encontrado.':'Nenhum candidato publicado pelo TSE até agora.'}</p>:<ol className="divide-y divide-[#eef0e9] px-5 sm:px-6">{candidates.slice(0,limit).map((candidate,index)=><li key={candidate.id} className="py-5"><div className="flex items-start gap-3"><span className={`candidate-number ${index===0&&!search?'first':''}`}>{candidate.number}</span><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><h3 className="break-words text-sm font-semibold leading-snug sm:text-base">{candidate.name}</h3><p className="mt-1 text-xs text-[#748077]">{candidate.party} <span className="mx-1 text-[#c2c9bd]">·</span> {integer.format(candidate.votes)} votos</p></div><p className="shrink-0 font-mono text-lg font-semibold tracking-[-.04em] sm:text-xl">{pct(candidate.percent)}</p></div>{(candidate.status||candidate.voteStatus!=='Válido')&&<div className="mt-2 flex flex-wrap gap-2">{candidate.status&&<span className="inline-flex items-center gap-1 rounded-md bg-[#eef4df] px-2 py-1 text-[10px] font-medium text-[#43552e]">{candidate.status.startsWith('Eleito')&&<Check size={11}/>} {candidate.status}</span>}{candidate.voteStatus&&candidate.voteStatus!=='Válido'&&<span className="rounded-md bg-[#f5f2e9] px-2 py-1 text-[10px] text-[#756b53]">{candidate.voteStatus}</span>}</div>}<div className="mt-3 h-1.5 overflow-hidden rounded-full bg-[#eff1e9]"><div className={`h-full rounded-full ${index===0&&!search?'bg-[#617c4c]':'bg-[#bac5a7]'}`} style={{width:`${Math.min(100,candidate.percent??0)}%`}}/></div></div></div></li>)}</ol>}
          {candidates.length>limit&&<button className="mx-5 mb-5 flex w-[calc(100%-2.5rem)] items-center justify-center gap-2 rounded-lg border border-[#dfe4d5] py-3 text-sm font-medium hover:bg-[#f5f7ef]" onClick={()=>setLimit(limit+40)}>Mostrar mais candidatos <ChevronDown size={15}/></button>}
          <div className="border-t border-[#eceee7] px-5 py-4 text-[11px] leading-relaxed text-[#748077]">Percentuais de candidatos reproduzidos do TSE.{filters.office===1&&filters.uf!=='br'?' Este recorte mostra os votos do estado; a eleição presidencial é decidida pelo resultado nacional.':''} {proportional?'A eleição de deputados também depende das regras de distribuição de vagas. A posição nesta lista não indica eleição.':'O resultado é parcial até a conclusão da totalização.'}</div>
        </section>
        <aside className="grid gap-5"><section className="rounded-2xl border border-[#e0e2d9] bg-[#fbfaf6] p-5 sm:p-6"><h2 className="mb-5 text-sm font-semibold">Retrato da votação</h2><div className="mb-5 border-b border-[#e0e2d9] pb-5"><p className="text-xs text-[#748077]">Votos registrados</p><p className="mt-1 font-mono text-[27px] font-medium tracking-[-.05em]">{data?.released?integer.format(data.votes.total):'—'}</p></div><dl className="grid gap-4">{[{label:'Válidos',value:data?.votes.valid,percent:data?.votes.validPercent,color:'#617c4c'},{label:'Brancos',value:data?.votes.blank,percent:data?.votes.blankPercent,color:'#bcc6ad'},{label:'Nulos',value:data?.votes.null,percent:data?.votes.nullPercent,color:'#859584'}].map(row=><div key={row.label} className="flex items-start justify-between gap-2"><dt className="flex items-center gap-2 text-sm text-[#69766b]"><span className="h-2 w-2 rounded-full" style={{backgroundColor:row.color}}/>{row.label}</dt><dd className="text-right"><p className="font-mono text-sm font-semibold">{data?.released?pct(row.percent):'—'}</p><p className="mt-0.5 text-[11px] text-[#7d8779]">{data?.released?integer.format(row.value??0):'—'} votos</p></dd></div>)}</dl><p className="mt-4 text-[10px] leading-relaxed text-[#7d8779]">Percentuais deste quadro calculados sobre os votos registrados. Votos anulados ou sub judice podem compor outras categorias.</p><div className="mt-5 grid grid-cols-2 gap-2 border-t border-[#e0e2d9] pt-5"><div><p className="text-[11px] text-[#748077]">Comparecimento</p><p className="mt-1 font-mono text-xl font-medium">{data?pct(data.voters.turnoutPercent):'—'}</p><p className="mt-1 text-[10px] text-[#748077]">{data?integer.format(data.voters.turnout):'—'} eleitores</p></div><div><p className="text-[11px] text-[#748077]">Abstenção</p><p className="mt-1 font-mono text-xl font-medium">{data?pct(data.voters.abstentionPercent):'—'}</p><p className="mt-1 text-[10px] text-[#748077]">{data?integer.format(data.voters.abstention):'—'} eleitores</p></div></div><p className="mt-3 text-[10px] text-[#7d8779]">Nas seções com dados de eleitorado apurados.</p></section>
          {filters.office===5&&<section className="rounded-2xl bg-[#eaf0dc] p-5"><h2 className="mb-2 flex items-center gap-2 text-sm font-semibold"><CheckCheck size={17}/>Senado: duas vagas</h2><p className="text-xs leading-relaxed text-[#63734e]">Cada eleitor pode votar em dois candidatos. O percentual do TSE representa a participação nos votos a candidatos, não a parcela dos eleitores.</p></section>}
          <section className="rounded-2xl border border-[#e0e2d9] bg-white p-5"><div className="mb-4 flex items-center justify-between"><h2 className="text-sm font-semibold">Sempre atualizado</h2><RefreshCw size={16} className={loading?'animate-spin text-[#71816c]':'text-[#71816c]'}/></div><p className="text-xs leading-relaxed text-[#748077]">Consulta automática a cada 60 segundos enquanto esta página estiver aberta.</p><button onClick={()=>void load()} disabled={loading||offline} className="mt-4 flex min-h-11 w-full items-center justify-center gap-2 rounded-xl bg-[#eef3e2] px-4 py-3 text-xs font-semibold text-[#3f552c] transition-colors hover:bg-[#e2eccf] disabled:opacity-50"><RefreshCw size={14}/>{loading?'Consultando…':'Atualizar agora'}</button><p className="mt-2 text-center text-[10px] text-[#7d8779]">{data?`Consulta: ${time(data.fetchedAt)} · ${next>0?`cache por ${next}s`:'próxima atualização em breve'}`:'Consultas compartilhadas para poupar o TSE'}</p></section>
          <a className="group flex items-center justify-between rounded-2xl border border-[#e0e2d9] p-5 text-sm font-medium" href={officialUrl} target="_blank" rel="noopener noreferrer">Conferir no site do TSE <ArrowUpRight size={19} className="text-[#71816c] transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5"/></a>
        </aside>
      </div>
      <details className="mt-6 rounded-2xl border border-[#e0e2d9] px-5 py-4 text-sm"><summary className="flex cursor-pointer items-center justify-between gap-3 font-medium"><span className="flex items-center gap-2"><CircleHelp size={16} className="text-[#71816c]"/>Como ler os números</span><ChevronDown size={16}/></summary><div className="mt-4 space-y-3 text-xs leading-relaxed text-[#748077]"><p>“Urnas apuradas” usa a porcentagem de seções totalizadas publicada pelo TSE. Seções e eleitores têm tamanhos diferentes; 50% das urnas não significa 50% dos votos.</p><p>Estar na frente durante a apuração não garante vitória. Os rótulos “Eleito” e “2º turno” aparecem apenas quando publicados pelo TSE.</p><p>Comparecimento e abstenção consideram o eleitorado das seções já processadas. Os percentuais podem mudar conforme chegam novos dados.</p><p>Este é um painel independente do Grupo B. Os arquivos são consultados no domínio oficial do TSE; este painel não verifica a assinatura digital dos arquivos. Você pode conferir os números diretamente na fonte.</p><div className="flex flex-wrap gap-x-5 gap-y-3 pt-1"><a className="inline-flex items-center gap-1 underline underline-offset-4" href={data?.source??officialUrl} target="_blank" rel="noopener noreferrer">Arquivo oficial <ExternalLink size={11}/></a><a className="inline-flex items-center gap-1 underline underline-offset-4" href="https://www.tse.jus.br/eleicoes/informacoes-tecnicas-sobre-a-divulgacao-de-resultados" target="_blank" rel="noopener noreferrer">Documentação do TSE <ExternalLink size={11}/></a></div></div></details>
      <footer className="mt-8 flex flex-wrap items-center justify-between gap-3 text-[11px] text-[#87907f]"><span>Grupo B · Eleições 2026</span><span className="flex items-center gap-1.5"><ShieldCheck size={13}/>Dados oficiais. Painel independente.</span></footer>
    </main>
  </div>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
